apiVersion: apps/v1
kind: Deployment
metadata:
  name: login-ui
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: login-ui
  template:
    metadata:
      labels:
        app: login-ui
    spec:
      containers:
        name: login-ui
        ports:
        - containerPort: 80