apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: login-ui
spec:
  template:
    metadata:
      labels:
        app: login-ui
    spec:
      containers:
      - name: login-ui
        image: mabrmiura/login:1.1
        env:
        - name: REDISHOST
          value: "redisapp:6379"
        resources:
          requests:
            cpu: 25m
            memory: 50Mi
          limits:
            cpu: 150m
            memory: 150Mi
        ports:
        - containerPort: 8080
  selector:
    matchLabels:
      app: login-ui
  replicas: 6
  strategy:
    canary:
      steps:
      - setWeight: 10
      - pause: {}
      - setWeight: 50
      - pause: {}

kind: Application
metadata:
  annotations:
    notifications.argoproj.io/subscribe.cd-visibility-trigger.cd-visibility-webhook: ""
    dd_env: prod
    dd_service: login-service