name: Publish image to Docker Hub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          docker build . -t mabrmiura/login:latest
      - name: publish
        run: |
          docker login -u mabrmiura -p ${{ secrets.DOCKER_HUB_SECRET }}
          docker push mabrmiura/login:latest
