name: Publish image to Docker Hub
on:
  [workflow_dispatch]

jobs:
  publish_image:
    runs-on: macos-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: build
        run: |
          brew install docker
          colima start
          docker build . -t mabrmiura/login:latest
      - name: publish
        run: |
          docker push mabrmiura/login:latest
